version: "3.8"
services:
  mysql_hesias:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=exam_3jav
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306